### ISSUE TITLE
Avoid vendor prefixes

### ISSUE THREAD

**Issue by HugoGiraudel** [Penguin-Library/penguin#1]
Hey there!

I would argue it is not Penguin’s role to prefix the styles and this should be delayed to a third party library such as Autoprefixer. While I understand how having “all-in-one” is a good thing, Autoprefixer handles prefixing based on actual stats + configuration, which is better than hard-coded prefixes in a stylesheet.

If you want me to submit a PR to get rid of the prefixes, just ask. :)

**Comment by JoanClaret** [comment]
Completely agree. 
Actually we run  autoprefixer in the gulp task "sass" which is included in the repository.
it would be awesome if you could submit a PR in this library. Feel free to collaborate in any way you want!

**Comment by JoanClaret** [comment]
Merged PR.
Thanks!
