### ISSUE TITLE
Selector issue with bottom-gradient mixin

### ISSUE THREAD

**Issue by HugoGiraudel** [Penguin-Library/penguin#5]
Hi. Not sure what is going on with the ampersand selector here: https://github.com/Penguin-Library/penguin/blob/master/src/scss/_mixins.scss#L167-L168. :)

**Comment by JoanClaret** [comment]
i think i'm not undertanding you, can you please put an example?

**Comment by HugoGiraudel** [comment]
Sorry, wrong lines: https://github.com/Penguin-Library/penguin/blob/master/src/scss/_mixins.scss#L153-L154. :D

**Comment by JoanClaret** [comment]
Fixed. Thank you!
