### ISSUE TITLE
Missing webkit & moz attributes on .select select

### ISSUE THREAD

**Issue by axel-blade** [Penguin-Library/penguin#70]
The official site has `.select select` set with webkit- and moz-appearance: none not the src files found here on github.

Found on https://sierra-library.github.io/
```
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
```

Githubs src/components/_forms.scss
https://github.com/sierra-library/sierra/blob/3ec830cafecd98192bb9c375e7d8cb3e836f42b0/src/components/_forms.scss#L89-L91

**Comment by elboletaire** [comment]
The project automatically adds prefixes where they are needed in the output files. It's done using postcss auto-prefixer. 

Also, modern browsers don't need such prefixes. You can check it by yourself at MDN https://developer.mozilla.org/en-US/docs/Web/CSS/appearance. It's very probable that prefixes ain't output in this very specific case.

**Comment by axel-blade** [comment]
@elboletaire yes this was a user error by me. Sorry!
